### ISSUE TITLE
Add poisson distribution support?

### ISSUE THREAD

**Issue by jheer** [uwdata/vega-statistics#2]
Would require inclusion of gamma / log-gamma functions. Some options for those:
- http://picomath.org/javascript/gamma.js.html
- https://github.com/substack/gamma.js

**Comment by mcorrell** [comment]
The picomath implementation covers more cases than the substack implementation. In general I prefer the S&A approximation to the Lanzcos approximation, as it is better behaved with integer arguments for gamma (which should be exactly = (n-1)!). E.g. gamma_1(3) = 2, gamma_2(3) = 1.9999999999999996. 

If you do decide to include a gamma fn approximation, we could also get t-distributions as well, for only a little bit of extra work (we'd need a incomplete beta function approximation, of which I have several that I like, but that depend on a good gamma fn to work).
